version: '3.1'

services:
  books-db:
    image: postgres:13.3-alpine
    container_name: books-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
  price-db:
    image: postgres:13.3-alpine
    container_name: price-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: price