server:
  port: 8083
  servlet:
    context-path: /users
spring:
  application:
    name: backend-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
