server:
  port: 8081
  servlet:
    context-path: /books
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

