server:
  port: 8082
  servlet:
    context-path: /prices
spring:
  application:
    name: price-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
